[tool.poetry]
name = "soydngpnext"
version = "0.1.2"
description = "A Deeplearning driving bioinformatic toolkit."
authors = ["XtLab"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
